/**
 * Property tests generated by the `spec-correctness` skill.
 *
 * Source: `quire properties --scope . --json 'spec/**\/*.md'` (quire-cli 0.12.0).
 * Grounded against `src/org.ts` — `originOrg` and its `orgFromRemoteUrl` helper,
 * whose doc comment enumerates exactly the remote shapes that carry no org.
 */
import fc from "fast-check";

import { originOrg } from "../../src/org";

/** A git config declaring a single `origin` remote with the given url. */
function gitConfig(url: string): string {
  return `[core]\n\trepositoryformatversion = 0\n[remote "origin"]\n\turl = ${url}\n\tfetch = +refs/heads/*:refs/remotes/origin/*\n`;
}

const segment = fc.stringMatching(/^[a-z][a-z0-9-]{0,11}$/);

/**
 * The four families `orgFromRemoteUrl` documents as naming no org: an absolute
 * local path, a relative local path, a `file://` url, and a host-based url with
 * a single path segment.
 */
const orglessRemote = fc.oneof(
  segment.map((repo) => `/srv/git/${repo}.git`),
  segment.map((repo) => `../${repo}`),
  segment.map((repo) => `file:///srv/git/${repo}.git`),
  segment.map((repo) => `https://git.example.com/${repo}.git`),
);

/**
 * Trace: FR-025-AC-9 — a local-path remote and a host-based remote with no owner
 * segment each yield no organization, rather than a path segment or the host name.
 * spec-correctness: row=FR-025-AC-9 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-025-AC-9 remotes that name no organization", () => {
  test("never substitutes a path segment or the host name", () => {
    fc.assert(
      fc.property(orglessRemote, (url) => {
        expect(originOrg(gitConfig(url))).toBeUndefined();
      }),
    );
  });
});

/**
 * Trace: FR-025-AC-10 — a remote path with a nested namespace qualifies by the
 * segment immediately preceding the repository.
 * spec-correctness: row=FR-025-AC-10 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-025-AC-10 nested namespaces", () => {
  test("qualifies by the segment immediately preceding the repository, at any depth", () => {
    fc.assert(
      fc.property(fc.array(segment, { minLength: 2, maxLength: 6 }), (path) => {
        const url = `https://git.example.com/${path.join("/")}.git`;
        expect(originOrg(gitConfig(url))).toBe(path[path.length - 2]);
      }),
    );
  });

  test("holds for the scp-style form as it does for the https form", () => {
    fc.assert(
      fc.property(fc.array(segment, { minLength: 2, maxLength: 6 }), (path) => {
        const url = `git@git.example.com:${path.join("/")}.git`;
        expect(originOrg(gitConfig(url))).toBe(path[path.length - 2]);
      }),
    );
  });
});
