/**
 * Property tests generated by the `spec-correctness` skill.
 *
 * FR-005 error-case criteria: the negative domain is every bareword outside the
 * command graph oclif actually discovered, so the known set is read from the
 * loaded config rather than hard-coded — a hard-coded list would go stale the
 * moment a command is added and would silently stop testing anything.
 *
 * `numRuns` is reduced from the fast-check default of 100: each case dispatches
 * through the real oclif runner, and the negative domain is uniform enough that
 * 30 cases exercise it. Recorded in tests/props/QUEUE.md.
 */
import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { settings, type Config } from "@oclif/core";
import fc from "fast-check";

import { loadConfig, run } from "@agent-ix/ix-cli-core";

// The catalog/write handlers call ensureDefaultModules() internally, whose
// git-subdir sources would hit the network. Same stub the CLI suite uses.
vi.mock("../../src/modules", () => ({
  ensureDefaultModules: () => {},
  defaultModulesManifest: () => ({ schemaVersion: 1, entries: [] }),
}));

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

let config: Config;
let topLevel: Set<string>;
let catalogSubcommands: Set<string>;
let pluginSubcommands: Set<string>;

const PROP = { numRuns: 30 };
const bareword = fc.stringMatching(/^[a-z][a-z-]{0,11}$/);

beforeAll(async () => {
  settings.enableAutoTranspile = false;
  if (!existsSync(join(repoRoot, "dist", "commands", "update.js"))) {
    execSync("pnpm run build", { cwd: repoRoot, stdio: "inherit" });
  }
  config = await loadConfig({ root: repoRoot });

  const ids = config.commands.map((c) => c.id);
  topLevel = new Set(ids.map((id) => id.split(":")[0]));
  const subs = (topic: string) =>
    new Set(
      ids
        .filter((id) => id.startsWith(`${topic}:`))
        .map((id) => id.split(":")[1]),
    );
  catalogSubcommands = subs("catalog");
  pluginSubcommands = subs("plugin");
});

/**
 * Trace: FR-005-AC-1 — an unknown command raises an error that includes usage.
 * spec-correctness: row=FR-005-AC-1 property=error-case extraction=extractable origin=regex review=none
 */
describe("FR-005-AC-1 unknown top-level commands", () => {
  test("are rejected, for any bareword outside the discovered command graph", async () => {
    await fc.assert(
      fc.asyncProperty(bareword, async (cmd) => {
        fc.pre(!topLevel.has(cmd));
        await expect(run([cmd], config)).rejects.toThrow();
      }),
      PROP,
    );
  });

  test("are rejected by name — the error names the command that was not found", async () => {
    await fc.assert(
      fc.asyncProperty(bareword, async (cmd) => {
        fc.pre(!topLevel.has(cmd));
        // Containment, not a word-boundary regex: a generated bareword can end
        // in `-`, after which `\b` does not match. fast-check shrank to "a-".
        await expect(run([cmd], config)).rejects.toThrow(
          expect.objectContaining({
            message: expect.stringContaining(cmd),
          }) as Error,
        );
      }),
      PROP,
    );
  });
});

/**
 * Trace: FR-005-AC-2 — an unknown `catalog` subcommand raises an error.
 * spec-correctness: row=FR-005-AC-2 property=error-case extraction=extractable origin=regex review=none
 */
describe("FR-005-AC-2 unknown catalog subcommands", () => {
  test("are rejected, for any bareword the catalog topic does not declare", async () => {
    await fc.assert(
      fc.asyncProperty(bareword, async (sub) => {
        fc.pre(!catalogSubcommands.has(sub));
        await expect(run(["catalog", sub], config)).rejects.toThrow();
      }),
      PROP,
    );
  });
});

/**
 * Trace: FR-005-AC-3 — an unknown `plugin` subcommand raises an error.
 * spec-correctness: row=FR-005-AC-3 property=error-case extraction=extractable origin=regex review=none
 */
describe("FR-005-AC-3 unknown plugin subcommands", () => {
  test("are rejected, for any bareword the plugin topic does not declare", async () => {
    await fc.assert(
      fc.asyncProperty(bareword, async (sub) => {
        fc.pre(!pluginSubcommands.has(sub));
        await expect(run(["plugin", sub], config)).rejects.toThrow();
      }),
      PROP,
    );
  });
});
