/**
 * Property tests generated by the `spec-correctness` skill.
 *
 * Grounded against `src/version.ts:23` — `resolveVersion(baked)`, a two-branch
 * total function, so the property is total too.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import fc from "fast-check";

import { resolveVersion } from "../../src/version";

const packageJsonVersion = (
  JSON.parse(readFileSync(join(process.cwd(), "package.json"), "utf8")) as {
    version: string;
  }
).version;

/**
 * Trace: FR-002-AC-4 — a non-empty baked version is reported verbatim; an empty
 * one falls back to the `package.json` version.
 * spec-correctness: row=FR-002-AC-4 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-002-AC-4 baked version resolution", () => {
  test("reports any non-empty baked version verbatim, and only the empty one falls back", () => {
    fc.assert(
      fc.property(fc.string(), (baked) => {
        expect(resolveVersion(baked)).toBe(
          baked === "" ? packageJsonVersion : baked,
        );
      }),
    );
  });

  test("never rewrites, trims, or normalizes a baked version", () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1 }), (baked) => {
        expect(resolveVersion(baked)).toHaveLength(baked.length);
      }),
    );
  });
});
