/**
 * Property tests generated by the `spec-correctness` skill.
 *
 * Grounded against `src/plugins.ts` — `parseSourceArg`, whose final branch is the
 * unprefixed case FR-018-AC-5 describes.
 */
import fc from "fast-check";

import { parseSourceArg } from "../../src/plugins";

/**
 * Trace: FR-018-AC-5 — a bare argument maps to a path source.
 * spec-correctness: row=FR-018-AC-5 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-018-AC-5 unprefixed source arguments", () => {
  test("map to a path source carrying the argument verbatim", () => {
    fc.assert(
      fc.property(fc.string({ minLength: 1, maxLength: 40 }), (arg) => {
        fc.pre(!/^(path:|github:|package:)/.test(arg));
        expect(parseSourceArg(arg)).toEqual({ type: "path", path: arg });
      }),
    );
  });

  test("keeps a prefix that is not one of the three known ones", () => {
    fc.assert(
      fc.property(
        fc.stringMatching(/^[a-z]{2,10}$/),
        fc.stringMatching(/^[a-z./-]{1,20}$/),
        (scheme, rest) => {
          fc.pre(!["path", "github", "package"].includes(scheme));
          const arg = `${scheme}:${rest}`;
          expect(parseSourceArg(arg)).toEqual({ type: "path", path: arg });
        },
      ),
    );
  });
});
