/**
 * Property tests generated by the `spec-correctness` skill.
 *
 * Covers the catalog-assembly criteria of FR-006, FR-008, FR-009, FR-010 and
 * FR-012. Grounded against `src/catalog.ts` — `loadCatalog`, `locateModuleRoot`,
 * `skeletonPath`, `findDuplicates` and `findCatalogEntry`.
 *
 * Fixtures are built **once** and the generators range over which of them a case
 * uses, so no case touches the filesystem. A generator that wrote a module tree
 * per case would make the suite filesystem-bound for no extra coverage.
 */
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import fc from "fast-check";
import { stringify as stringifyYaml } from "yaml";

import { findCatalogEntry, loadCatalog } from "../../src/catalog";

function tmp(prefix: string): string {
  return mkdtempSync(join(tmpdir(), `quoin-props-${prefix}-`));
}

function writeModule(
  dir: string,
  body: Record<string, unknown>,
  files: Record<string, string> = {},
): string {
  mkdirSync(join(dir, "skeletons"), { recursive: true });
  writeFileSync(join(dir, "manifest.yaml"), stringifyYaml(body));
  for (const [file, content] of Object.entries(files)) {
    writeFileSync(join(dir, file), content);
  }
  return dir;
}

// ---- fixtures, built once ----------------------------------------------------

/** Six modules, each declaring the shared type `FR` plus a name-unique type. */
const sharedTypeRoots = [
  "alpha",
  "bravo",
  "charlie",
  "delta",
  "echo",
  "fox",
].map((name) =>
  writeModule(tmp(name), {
    name,
    artifact_types: [{ name: "FR" }, { name: `${name.toUpperCase()}Type` }],
    object_types: [{ name: "domain" }],
  }),
);

/** One module declaring types with no collision anywhere. */
const uniqueRoot = writeModule(tmp("unique"), {
  name: "solo",
  artifact_types: [{ name: "SoloArtifact" }],
  object_types: [{ name: "solo_object" }],
});

/** Candidates `locateModuleRoot` must skip: missing, empty dir, plain file. */
const missingCandidate = join(tmp("missing"), "does-not-exist");
const emptyCandidate = tmp("empty");
const fileCandidate = (() => {
  const dir = tmp("file");
  const path = join(dir, "not-a-module");
  writeFileSync(path, "");
  return path;
})();

/** One module per skeleton filename casing, so the casing rule can be ranged over. */
const casingRoots: Record<string, string> = Object.fromEntries(
  ["FR.md", "fr.md", "Fr.md", "fR.md"].map((filename) => [
    filename,
    writeModule(
      tmp(`casing-${filename.replace(".", "-")}`),
      { name: `casing-${filename}`, artifact_types: [{ name: "FR" }] },
      { [join("skeletons", filename)]: "# skeleton\n" },
    ),
  ]),
);

// ---- FR-006 ------------------------------------------------------------------

/**
 * Trace: FR-006-AC-4 — a missing path, an empty directory, and a file candidate
 * are skipped.
 * spec-correctness: row=FR-006-AC-4 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-006-AC-4 unusable module candidates", () => {
  const unusable = fc.constantFrom(
    missingCandidate,
    emptyCandidate,
    fileCandidate,
  );

  test("are skipped, in any quantity and any order, without throwing", () => {
    fc.assert(
      fc.property(fc.array(unusable, { maxLength: 12 }), (candidates) => {
        expect(loadCatalog(candidates).modules).toEqual([]);
      }),
    );
  });

  test("never suppress a usable module they are mixed with", () => {
    fc.assert(
      fc.property(
        fc.array(unusable, { maxLength: 8 }),
        fc.nat({ max: 8 }),
        (candidates, at) => {
          const mixed = [...candidates];
          mixed.splice(Math.min(at, mixed.length), 0, uniqueRoot);
          expect(loadCatalog(mixed).modules.map((m) => m.name)).toEqual([
            "solo",
          ]);
        },
      ),
    );
  });
});

// ---- FR-008 ------------------------------------------------------------------

/**
 * Trace: FR-008-AC-1 — a repeated module root is loaded only once.
 * spec-correctness: row=FR-008-AC-1 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-008-AC-1 repeated module roots", () => {
  test("load once however often, and in whatever order, they repeat", () => {
    fc.assert(
      fc.property(
        fc.array(fc.constantFrom(...sharedTypeRoots, uniqueRoot), {
          minLength: 1,
          maxLength: 16,
        }),
        (roots) => {
          const names = loadCatalog(roots).modules.map((m) => m.name);
          expect(names).toEqual([...new Set(names)]);
          expect(new Set(names).size).toBe(new Set(roots).size);
        },
      ),
    );
  });
});

/**
 * Trace: FR-008-AC-2 — a second module declaring an already-seen name is skipped,
 * including its types.
 * spec-correctness: row=FR-008-AC-2 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-008-AC-2 modules with a colliding declared name", () => {
  // Two distinct roots that both declare `name: twin`.
  const twinA = writeModule(tmp("twin-a"), {
    name: "twin",
    artifact_types: [{ name: "TwinA" }],
  });
  const twinB = writeModule(tmp("twin-b"), {
    name: "twin",
    artifact_types: [{ name: "TwinB" }],
  });

  test("contribute no entries, whichever of the two is seen first", () => {
    fc.assert(
      fc.property(fc.boolean(), (aFirst) => {
        const roots = aFirst ? [twinA, twinB] : [twinB, twinA];
        const catalog = loadCatalog(roots);
        expect(catalog.modules).toHaveLength(1);
        const names = catalog.entries.map((e) => e.name);
        expect(names).toEqual([aFirst ? "TwinA" : "TwinB"]);
      }),
    );
  });
});

// ---- FR-009 ------------------------------------------------------------------

/**
 * Trace: FR-009-AC-5 — a skeleton named with the type's own casing resolves, and
 * a filename in any other casing does not — on a case-insensitive filesystem as
 * on a case-sensitive one.
 * spec-correctness: row=FR-009-AC-5 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-009-AC-5 skeleton filename casing", () => {
  test("resolves exactly the type's own casing and its lowercase form", () => {
    fc.assert(
      fc.property(fc.constantFrom(...Object.keys(casingRoots)), (filename) => {
        const entry = loadCatalog([casingRoots[filename]]).entries.find(
          (e) => e.name === "FR",
        );
        const accepted = filename === "FR.md" || filename === "fr.md";
        expect(Boolean(entry?.skeletonPath)).toBe(accepted);
        // When it resolves, the path names the file that is actually on disk.
        if (accepted) expect(entry?.skeletonPath).toContain(filename);
      }),
    );
  });
});

// ---- FR-010 ------------------------------------------------------------------

/** Every casing of a string, from all-lower to all-upper and every mix between. */
const anyCasingOf = (name: string): fc.Arbitrary<string> =>
  fc
    .array(fc.boolean(), { minLength: name.length, maxLength: name.length })
    .map((upper) =>
      [...name]
        .map((ch, i) => (upper[i] ? ch.toUpperCase() : ch.toLowerCase()))
        .join(""),
    );

/**
 * Trace: FR-010-AC-2 — a mixed-case request such as `DOMAIN` resolves the object
 * entry.
 * spec-correctness: row=FR-010-AC-2 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-010-AC-2 case-insensitive type lookup", () => {
  const catalog = loadCatalog([uniqueRoot, ...sharedTypeRoots]);

  test("resolves a known type under any casing whatsoever", () => {
    fc.assert(
      fc.property(
        fc
          .constantFrom(...catalog.entries.map((e) => e.name))
          .chain((name) => anyCasingOf(name).map((recased) => [name, recased])),
        ([name, recased]) => {
          expect(findCatalogEntry(catalog, recased)?.name).toBe(name);
        },
      ),
    );
  });

  test("resolves nothing for a name no casing of which is declared", () => {
    fc.assert(
      fc.property(fc.stringMatching(/^[a-z]{4,12}$/), (name) => {
        const declared = new Set(
          catalog.entries.map((e) => e.name.toLowerCase()),
        );
        fc.pre(!declared.has(name));
        expect(findCatalogEntry(catalog, name)).toBeUndefined();
      }),
    );
  });
});

// ---- FR-012 ------------------------------------------------------------------

/**
 * Trace: FR-012-AC-1 — a type declared by two modules is reported as a duplicate
 * with the declaring modules sorted.
 * spec-correctness: row=FR-012-AC-1 property=ordering extraction=extractable origin=regex review=none
 */
describe("FR-012-AC-1 duplicate type reporting", () => {
  test("lists the declaring modules in sorted order, whatever order the roots arrive in", () => {
    fc.assert(
      fc.property(
        fc.uniqueArray(fc.constantFrom(...sharedTypeRoots), { minLength: 2 }),
        (roots) => {
          for (const dup of loadCatalog(roots).duplicates) {
            expect(dup.modules).toEqual([...dup.modules].sort());
          }
        },
      ),
    );
  });

  test("reports the shared type once, naming every declaring module", () => {
    fc.assert(
      fc.property(
        fc.uniqueArray(fc.constantFrom(...sharedTypeRoots), { minLength: 2 }),
        (roots) => {
          const catalog = loadCatalog(roots);
          const fr = catalog.duplicates.filter((d) => d.name === "FR");
          expect(fr).toHaveLength(1);
          expect(fr[0].modules).toHaveLength(roots.length);
        },
      ),
    );
  });
});

/**
 * Trace: FR-012-AC-2 — a catalog with unique type names reports no duplicates.
 * spec-correctness: row=FR-012-AC-2 property=universal extraction=extractable origin=regex review=none
 */
describe("FR-012-AC-2 catalogs with no collision", () => {
  test("report no duplicates for any single module root", () => {
    fc.assert(
      fc.property(fc.constantFrom(uniqueRoot, ...sharedTypeRoots), (root) => {
        expect(loadCatalog([root]).duplicates).toEqual([]);
      }),
    );
  });
});
