/**
 * Property tests generated by the `spec-correctness` skill.
 *
 * Covers FR-013-AC-4 and FR-015-AC-2/AC-3. Grounded against `src/write.ts` —
 * `createAuthoringPack`'s unknown-type throw (which sorts the available-type
 * list) and its `validation.command`, which is the only observable of the
 * unexported `shellQuote`.
 */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import fc from "fast-check";
import { stringify as stringifyYaml } from "yaml";

import { loadCatalog, type SpecCatalog } from "../../src/catalog";
import { createAuthoringPack } from "../../src/write";

// Every scratch dir is tracked so the file can remove them all. fast-check runs
// each property many times; an untracked mkdtemp per case leaks hundreds of
// directories into /tmp per suite run.
const scratch: string[] = [];
/** The message of the error a thunk throws; fails the test if it throws nothing. */
function messageOf(thunk: () => unknown): string {
  try {
    thunk();
  } catch (error) {
    return (error as Error).message;
  }
  throw new Error("expected the call to throw, but it returned");
}

function tmp(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), `quoin-props-${prefix}-`));
  scratch.push(dir);
  return dir;
}

afterAll(() => {
  for (const dir of scratch) rmSync(dir, { recursive: true, force: true });
});

const moduleRoot = (() => {
  const dir = tmp("write");
  mkdirSync(join(dir, "skeletons"), { recursive: true });
  writeFileSync(
    join(dir, "manifest.yaml"),
    stringifyYaml({
      name: "props",
      artifact_types: [
        { name: "FR" },
        { name: "NFR" },
        { name: "StR" },
        { name: "ADR" },
      ],
      object_types: [{ name: "domain" }, { name: "entity" }],
    }),
  );
  return dir;
})();

const catalog: SpecCatalog = loadCatalog([moduleRoot]);
const declared = new Set(catalog.entries.map((e) => e.name.toLowerCase()));

/** `resolveOrg` reads the repo's git config; a bare temp dir has none. */
const repoDir = tmp("repo");

// ---- FR-013 ------------------------------------------------------------------

describe("FR-013-AC-4 unknown type errors", () => {
  /**
   * Trace: FR-013-AC-4 — an unknown type raises an error listing available types in
   * sorted order.
   * spec-correctness: row=FR-013-AC-4 property=ordering extraction=extractable origin=regex review=none
   */
  test("list the available types in sorted order, for any unknown name", () => {
    fc.assert(
      fc.property(fc.stringMatching(/^[a-z]{3,12}$/), (name) => {
        fc.pre(!declared.has(name));
        // Assert the throw explicitly: a silent try/catch would leave `message`
        // empty and fail later with a confusing TypeError instead of "expected
        // a throw".
        expect(() => createAuthoringPack(catalog, repoDir, [name])).toThrow(
          /Available types: /,
        );
        const message = messageOf(() =>
          createAuthoringPack(catalog, repoDir, [name]),
        );
        const listed = message.split("Available types: ")[1].split(", ");
        expect(listed).toEqual([...listed].sort((a, b) => a.localeCompare(b)));
      }),
    );
  });

  test("name every declared type, whichever unknown name was requested", () => {
    fc.assert(
      fc.property(fc.stringMatching(/^[a-z]{3,12}$/), (name) => {
        fc.pre(!declared.has(name));
        // Assert the throw explicitly: a silent try/catch would leave `message`
        // empty and fail later with a confusing TypeError instead of "expected
        // a throw".
        expect(() => createAuthoringPack(catalog, repoDir, [name])).toThrow(
          /Available types: /,
        );
        const message = messageOf(() =>
          createAuthoringPack(catalog, repoDir, [name]),
        );
        const listed = message.split("Available types: ")[1].split(", ");
        expect(new Set(listed)).toEqual(
          new Set(catalog.entries.map((e) => e.name)),
        );
      }),
    );
  });
});

// ---- FR-015 ------------------------------------------------------------------

/** The scope argument as it is rendered into `validation.command`. */
function renderedScope(dir: string): string {
  const { validation } = createAuthoringPack(catalog, dir, ["FR"]);
  return validation.command.slice(
    "quire validate --scope ".length,
    validation.command.indexOf(' "spec/**/*.md"'),
  );
}

/** Repo directory names spanning both sides of the quoting predicate. */
const repoDirArb = fc
  .oneof(
    fc.stringMatching(/^[A-Za-z0-9_.-]{1,12}$/),
    fc.stringMatching(/^[A-Za-z0-9]{1,6} [A-Za-z0-9]{1,6}$/),
    fc.stringMatching(/^[A-Za-z0-9]{1,6}'[A-Za-z0-9]{1,6}$/),
    fc.stringMatching(/^[A-Za-z0-9]{1,6}[()&;$]{1,2}[A-Za-z0-9]{1,6}$/),
  )
  .map((name) => {
    const dir = join(tmp("scope"), name);
    mkdirSync(dir, { recursive: true });
    return dir;
  });

describe("FR-015-AC-2/AC-3 shell quoting of the repo path", () => {
  /**
   * Trace: FR-015-AC-2 — a clean repo path is rendered without surrounding quotes.
   * Trace: FR-015-AC-3 — a repo path containing a space is single-quoted.
   * spec-correctness: row=FR-015-AC-2 property=universal extraction=extractable origin=regex review=none
   * spec-correctness: row=FR-015-AC-3 property=universal extraction=extractable origin=regex review=none
   */
  test("quotes exactly the paths the shell-safe predicate rejects", () => {
    fc.assert(
      fc.property(repoDirArb, (dir) => {
        const shellSafe = /^[A-Za-z0-9_./:-]+$/.test(resolve(dir));
        expect(renderedScope(dir).startsWith("'")).toBe(!shellSafe);
      }),
      { numRuns: 40 },
    );
  });

  test("round-trips the path: unquoting the rendering yields the resolved path", () => {
    fc.assert(
      fc.property(repoDirArb, (dir) => {
        const rendered = renderedScope(dir);
        const unquoted = rendered.startsWith("'")
          ? rendered.slice(1, -1).replaceAll("'\\''", "'")
          : rendered;
        expect(unquoted).toBe(resolve(dir));
      }),
      { numRuns: 40 },
    );
  });
});
