/**
 * Second-pass property tests generated by the `spec-correctness` skill.
 *
 * These criteria were classified `not-extractable` — the deterministic pass read
 * them as concrete examples. Grounding them against `src/` found a real domain
 * behind each, so they are **reclassified** proposals, not engine misses: the
 * classifier is at its measured ceiling and this is the residue it hands over.
 *
 * ACCEPTED 2026-08-08: each oracle was checked against its cited source line and
 * the suite runs green. The row_id tags are byte-identical to the queued form —
 * only the skip marker and `review=` changed.
 * See tests/props/QUEUE.md for the acceptance procedure.
 */
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import fc from "fast-check";

import { defaultModuleRoots, loadCatalog } from "../../src/catalog";
import { QuoinConfigSchema } from "../../src/config-schema";
import { originOrg } from "../../src/org";
import { parseSourceArg } from "../../src/plugins";
import { createAuthoringPack, parseTypeList } from "../../src/write";

const segment = fc.stringMatching(/^[a-z][a-z0-9-]{0,11}$/);

// See fr-catalog.prop.test.ts: a per-case mkdtemp leaks without this.
const scratch: string[] = [];
function scratchDir(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  scratch.push(dir);
  return dir;
}

afterAll(() => {
  for (const dir of scratch) rmSync(dir, { recursive: true, force: true });
});

function gitConfig(url: string, section = '[remote "origin"]'): string {
  return `[core]\n\trepositoryformatversion = 0\n${section}\n\turl = ${url}\n`;
}

// ---- FR-013-AC-3 -------------------------------------------------------------

describe("FR-013-AC-3 type-list parsing", () => {
  const padded = fc
    .tuple(
      fc.stringMatching(/^[ \t]{0,3}$/),
      segment,
      fc.stringMatching(/^[ \t]{0,3}$/),
    )
    .map(([before, name, after]) => ({
      name,
      raw: `${before}${name}${after}`,
    }));

  /**
   * Trace: FR-013-AC-3 — type values are comma-split, trimmed, and emptied entries
   * dropped.
   * spec-correctness: row=FR-013-AC-3 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `universal`. Grounded on src/write.ts:42 `parseTypeList`, a total
   * pure function over `string | string[] | undefined` — the criterion describes a
   * whole domain, not the one example the classifier read.
   */
  test("yields exactly the non-empty trimmed names, for any comma list", () => {
    fc.assert(
      fc.property(fc.array(padded, { maxLength: 12 }), (items) => {
        expect(parseTypeList(items.map((i) => i.raw).join(","))).toEqual(
          items.map((i) => i.name),
        );
      }),
    );
  });

  test("drops every empty entry however many separators there are", () => {
    fc.assert(
      fc.property(fc.array(fc.constant(""), { maxLength: 8 }), (empties) => {
        expect(parseTypeList(empties.join(","))).toEqual([]);
      }),
    );
  });

  test("treats an array argument as the concatenation of its comma lists", () => {
    fc.assert(
      fc.property(
        fc.array(fc.array(segment, { maxLength: 3 }), { maxLength: 4 }),
        (groups) => {
          expect(parseTypeList(groups.map((g) => g.join(",")))).toEqual(
            groups.flat(),
          );
        },
      ),
    );
  });
});

// ---- FR-018-AC-1..AC-4 -------------------------------------------------------

describe("FR-018-AC-1..AC-4 plugin source parsing", () => {
  /**
   * Trace: FR-018-AC-1 — `path:<dir>` maps to a path source.
   * Trace: FR-018-AC-2 — `github:<owner>/<repo>[@<ref>]` maps to a GitHub source with optional ref.
   * Trace: FR-018-AC-3 — `github:<owner>/<repo>//<subdir>[@<ref>]` maps to a git-subdir source.
   * Trace: FR-018-AC-4 — `package:<pkg>[@<ver>]` maps to an npm source split on the final `@`.
   * spec-correctness: row=FR-018-AC-1 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   * spec-correctness: row=FR-018-AC-2 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   * spec-correctness: row=FR-018-AC-3 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   * spec-correctness: row=FR-018-AC-4 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `universal`. Each criterion states a total rule over its prefix,
   * grounded on src/plugins.ts:34 `parseSourceArg`. The classifier read the inline
   * `<placeholder>` syntax as a concrete example.
   */
  test("FR-018-AC-1 `path:` carries the remainder verbatim, whatever it contains", () => {
    fc.assert(
      fc.property(fc.string({ maxLength: 40 }), (rest) => {
        expect(parseSourceArg(`path:${rest}`)).toEqual({
          type: "path",
          path: rest,
        });
      }),
    );
  });

  test("FR-018-AC-2 `github:` yields owner/repo, and the ref only when one is given", () => {
    fc.assert(
      fc.property(
        segment,
        segment,
        fc.option(segment, { nil: undefined }),
        (owner, repo, ref) => {
          const arg = `github:${owner}/${repo}${ref ? `@${ref}` : ""}`;
          expect(parseSourceArg(arg)).toEqual({
            type: "github",
            repo: `${owner}/${repo}`,
            ref,
          });
        },
      ),
    );
  });

  test("FR-018-AC-3 a `//` in the spec always yields git-subdir, split at the first `//`", () => {
    fc.assert(
      fc.property(
        segment,
        segment,
        segment,
        fc.option(segment, { nil: undefined }),
        (owner, repo, sub, ref) => {
          const arg = `github:${owner}/${repo}//${sub}${ref ? `@${ref}` : ""}`;
          expect(parseSourceArg(arg)).toEqual({
            type: "git-subdir",
            url: `${owner}/${repo}`,
            path: sub,
            ref,
          });
        },
      ),
    );
  });

  test("FR-018-AC-4 `package:` splits on the FINAL `@`, so a scoped package keeps its scope", () => {
    fc.assert(
      fc.property(
        segment,
        segment,
        fc.option(segment, { nil: undefined }),
        (scope, name, version) => {
          const pkg = `@${scope}/${name}`;
          const arg = `package:${pkg}${version ? `@${version}` : ""}`;
          expect(parseSourceArg(arg)).toEqual(
            version
              ? { type: "npm", package: pkg, version }
              : { type: "npm", package: pkg },
          );
        },
      ),
    );
  });
});

// ---- FR-025-AC-2, AC-3, AC-11 ------------------------------------------------

describe("FR-025-AC-2/AC-3 remote url forms", () => {
  /**
   * Trace: FR-025-AC-2 — the organization is parsed from an SSH remote URL.
   * Trace: FR-025-AC-3 — the organization is parsed from an HTTPS remote URL.
   * spec-correctness: row=FR-025-AC-2 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   * spec-correctness: row=FR-025-AC-3 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `universal`. Grounded on src/org.ts:190 `originOrg`: each url form
   * is a family, not a single url.
   */
  test("AC-2 the scp-style form yields the owner for any host, owner and repo", () => {
    fc.assert(
      fc.property(
        segment,
        segment,
        segment,
        fc.boolean(),
        (host, owner, repo, dotGit) => {
          const url = `git@${host}.example.com:${owner}/${repo}${dotGit ? ".git" : ""}`;
          expect(originOrg(gitConfig(url))).toBe(owner);
        },
      ),
    );
  });

  test("AC-3 the https form yields the owner, with or without a port or `.git`", () => {
    fc.assert(
      fc.property(
        segment,
        segment,
        fc.option(fc.integer({ min: 1, max: 65535 }), { nil: undefined }),
        fc.boolean(),
        (owner, repo, port, dotGit) => {
          const url = `https://git.example.com${port ? `:${port}` : ""}/${owner}/${repo}${dotGit ? ".git" : ""}`;
          expect(originOrg(gitConfig(url))).toBe(owner);
        },
      ),
    );
  });
});

describe("FR-025-AC-11 section and remote name casing", () => {
  const casingsOf = (word: string) =>
    fc
      .array(fc.boolean(), { minLength: word.length, maxLength: word.length })
      .map((up) =>
        [...word]
          .map((c, i) => (up[i] ? c.toUpperCase() : c.toLowerCase()))
          .join(""),
      );

  /**
   * Trace: FR-025-AC-11 — the configuration's section name matches
   * case-insensitively and the quoted remote name case-sensitively.
   * spec-correctness: row=FR-025-AC-11 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `universal` over casings — the source comment at src/org.ts:193
   * states the asymmetry explicitly, which is the oracle.
   */
  test("any casing of the section name `remote` still resolves the org", () => {
    fc.assert(
      fc.property(casingsOf("remote"), segment, (section, owner) => {
        const config = gitConfig(
          `https://git.example.com/${owner}/repo.git`,
          `[${section} "origin"]`,
        );
        expect(originOrg(config)).toBe(owner);
      }),
    );
  });

  test("any casing of the remote name other than `origin` resolves nothing", () => {
    fc.assert(
      fc.property(casingsOf("origin"), segment, (name, owner) => {
        fc.pre(name !== "origin");
        const config = gitConfig(
          `https://git.example.com/${owner}/repo.git`,
          `[remote "${name}"]`,
        );
        expect(originOrg(config)).toBeUndefined();
      }),
    );
  });
});

// ---- FR-013-AC-2 -------------------------------------------------------------

describe("FR-013-AC-2 unusable repo directories", () => {
  const catalog = loadCatalog([]);

  const notADirectory = fc.oneof(
    segment.map((name) => join(scratchDir("quoin-p2-"), name)),
    segment.map((name) => {
      const path = join(scratchDir("quoin-p2-"), name);
      writeFileSync(path, "");
      return path;
    }),
  );

  /**
   * Trace: FR-013-AC-2 — a missing `repo_dir`, a non-existent path, and a file path
   * each raise an error.
   * spec-correctness: row=FR-013-AC-2 property=universal extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `error-case`. Grounded on src/write.ts:60 — the negative domain is
   * every path that is not an existing directory.
   */
  test("raise, naming the offending path, for any path that is not a directory", () => {
    fc.assert(
      fc.property(notADirectory, (dir) => {
        expect(() => createAuthoringPack(catalog, dir, ["FR"])).toThrow(
          expect.objectContaining({
            message: expect.stringContaining(dir),
          }) as Error,
        );
      }),
      { numRuns: 40 },
    );
  });
});

// ---- FR-007-AC-2 -------------------------------------------------------------

describe("FR-007-AC-2 empty module-path entries", () => {
  const saved = process.env.QUOIN_MODULE_PATHS;
  afterEach(() => {
    if (saved === undefined) delete process.env.QUOIN_MODULE_PATHS;
    else process.env.QUOIN_MODULE_PATHS = saved;
  });

  /**
   * Trace: FR-007-AC-2 — empty `QUOIN_MODULE_PATHS` entries are dropped.
   * spec-correctness: row=FR-007-AC-2 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `universal`. Grounded on src/catalog.ts:46 — `.filter(Boolean)`
   * over a `:`-split, so the rule holds for any arrangement of separators.
   */
  test("are dropped, leaving exactly the non-empty ones in order", () => {
    fc.assert(
      fc.property(
        fc.array(
          fc.oneof(
            fc.constant(""),
            segment.map((s) => `/tmp/${s}`),
          ),
          {
            maxLength: 10,
          },
        ),
        (entries) => {
          process.env.QUOIN_MODULE_PATHS = entries.join(":");
          const home = scratchDir("quoin-p2-home-");
          expect(defaultModuleRoots(home)).toEqual(entries.filter(Boolean));
        },
      ),
      { numRuns: 40 },
    );
  });
});

// ---- FR-027-AC-6 -------------------------------------------------------------

describe("FR-027-AC-6 strict configuration schema", () => {
  /**
   * Trace: FR-027-AC-6 — the declared schema is strict, so storing an unrecognized
   * key is rejected.
   * spec-correctness: row=FR-027-AC-6 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `error-case`. Grounded on src/config-schema.ts:15 — `.strict()`,
   * so the negative domain is every key other than `org`.
   */
  test("rejects any key that is not `org`", () => {
    fc.assert(
      fc.property(segment, fc.string({ maxLength: 20 }), (key, value) => {
        fc.pre(key !== "org");
        expect(QuoinConfigSchema.safeParse({ [key]: value }).success).toBe(
          false,
        );
      }),
    );
  });

  test("accepts any non-empty org, and rejects the empty one", () => {
    fc.assert(
      fc.property(fc.string({ maxLength: 30 }), (org) => {
        expect(QuoinConfigSchema.safeParse({ org }).success).toBe(
          org.length > 0,
        );
      }),
    );
  });
});
