/**
 * Second-pass property tests generated by the `spec-correctness` skill.
 *
 * These criteria were classified `not-extractable` — the deterministic pass read
 * them as concrete examples. Grounding them against `src/` found a real domain
 * behind each, so they are **reclassified** proposals, not engine misses: the
 * classifier is at its measured ceiling and this is the residue it hands over.
 *
 * ACCEPTED 2026-08-08: each oracle was checked against its cited source line and
 * the suite runs green. The row_id tags are byte-identical to the queued form —
 * only the skip marker and `review=` changed.
 * Emitted by the review-gated second pass; each test's provenance line carries
 * `origin=llm-second-pass` and its own confidence.
 *
 * quoin#446 removed the FR-018-AC-1..AC-4 and FR-025-AC-2/AC-3/AC-11 sections
 * along with the `src/plugins.ts` and `src/org.ts` they were grounded on. The
 * properties themselves were not dropped: they are restated over the same
 * families in `quoin-modules`' `tc_446_062`..`tc_446_065` and `quoin-config`'s
 * `tc_446_050`..`tc_446_053`, as exhaustive loops over a bounded domain with an
 * explicit population-floor assertion, because the Rust tree carries no
 * property-testing dependency and a cutover is not the place to add one.
 */
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import fc from "fast-check";

import { defaultModuleRoots, loadCatalog } from "../../src/catalog";
import { QuoinConfigSchema } from "../../src/config-schema";
import { createAuthoringPack, parseTypeList } from "../../src/write";

const segment = fc.stringMatching(/^[a-z][a-z0-9-]{0,11}$/);

// See fr-catalog.prop.test.ts: a per-case mkdtemp leaks without this.
const scratch: string[] = [];
function scratchDir(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  scratch.push(dir);
  return dir;
}

afterAll(() => {
  for (const dir of scratch) rmSync(dir, { recursive: true, force: true });
});

// ---- FR-013-AC-3 -------------------------------------------------------------

describe("FR-013-AC-3 type-list parsing", () => {
  const padded = fc
    .tuple(
      fc.stringMatching(/^[ \t]{0,3}$/),
      segment,
      fc.stringMatching(/^[ \t]{0,3}$/),
    )
    .map(([before, name, after]) => ({
      name,
      raw: `${before}${name}${after}`,
    }));

  /**
   * Trace: FR-013-AC-3 — type values are comma-split, trimmed, and emptied entries
   * dropped.
   * spec-correctness: row=FR-013-AC-3 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `universal`. Grounded on src/write.ts:42 `parseTypeList`, a total
   * pure function over `string | string[] | undefined` — the criterion describes a
   * whole domain, not the one example the classifier read.
   */
  test("yields exactly the non-empty trimmed names, for any comma list", () => {
    fc.assert(
      fc.property(fc.array(padded, { maxLength: 12 }), (items) => {
        expect(parseTypeList(items.map((i) => i.raw).join(","))).toEqual(
          items.map((i) => i.name),
        );
      }),
    );
  });

  test("drops every empty entry however many separators there are", () => {
    fc.assert(
      fc.property(fc.array(fc.constant(""), { maxLength: 8 }), (empties) => {
        expect(parseTypeList(empties.join(","))).toEqual([]);
      }),
    );
  });

  test("treats an array argument as the concatenation of its comma lists", () => {
    fc.assert(
      fc.property(
        fc.array(fc.array(segment, { maxLength: 3 }), { maxLength: 4 }),
        (groups) => {
          expect(parseTypeList(groups.map((g) => g.join(",")))).toEqual(
            groups.flat(),
          );
        },
      ),
    );
  });
});

// ---- FR-013-AC-2 -------------------------------------------------------------

describe("FR-013-AC-2 unusable repo directories", () => {
  const catalog = loadCatalog([]);

  const notADirectory = fc.oneof(
    segment.map((name) => join(scratchDir("quoin-p2-"), name)),
    segment.map((name) => {
      const path = join(scratchDir("quoin-p2-"), name);
      writeFileSync(path, "");
      return path;
    }),
  );

  /**
   * Trace: FR-013-AC-2 — a missing `repo_dir`, a non-existent path, and a file path
   * each raise an error.
   * spec-correctness: row=FR-013-AC-2 property=universal extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `error-case`. Grounded on src/write.ts:60 — the negative domain is
   * every path that is not an existing directory.
   */
  test("raise, naming the offending path, for any path that is not a directory", () => {
    fc.assert(
      fc.property(notADirectory, (dir) => {
        expect(() => createAuthoringPack(catalog, dir, ["FR"])).toThrow(
          expect.objectContaining({
            message: expect.stringContaining(dir),
          }) as Error,
        );
      }),
      { numRuns: 40 },
    );
  });
});

// ---- FR-007-AC-2 -------------------------------------------------------------

describe("FR-007-AC-2 empty module-path entries", () => {
  const saved = process.env.QUOIN_MODULE_PATHS;
  afterEach(() => {
    if (saved === undefined) delete process.env.QUOIN_MODULE_PATHS;
    else process.env.QUOIN_MODULE_PATHS = saved;
  });

  /**
   * Trace: FR-007-AC-2 — empty `QUOIN_MODULE_PATHS` entries are dropped.
   * spec-correctness: row=FR-007-AC-2 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `universal`. Grounded on src/catalog.ts:46 — `.filter(Boolean)`
   * over a `:`-split, so the rule holds for any arrangement of separators.
   */
  test("are dropped, leaving exactly the non-empty ones in order", () => {
    fc.assert(
      fc.property(
        fc.array(
          fc.oneof(
            fc.constant(""),
            segment.map((s) => `/tmp/${s}`),
          ),
          {
            maxLength: 10,
          },
        ),
        (entries) => {
          process.env.QUOIN_MODULE_PATHS = entries.join(":");
          const home = scratchDir("quoin-p2-home-");
          expect(defaultModuleRoots(home)).toEqual(entries.filter(Boolean));
        },
      ),
      { numRuns: 40 },
    );
  });
});

// ---- FR-027-AC-6 -------------------------------------------------------------

describe("FR-027-AC-6 strict configuration schema", () => {
  /**
   * Trace: FR-027-AC-6 — the declared schema is strict, so storing an unrecognized
   * key is rejected.
   * spec-correctness: row=FR-027-AC-6 property=example extraction=not-extractable origin=llm-second-pass review=accepted confidence=high
   *
   * Reclassified `error-case`. Grounded on src/config-schema.ts:15 — `.strict()`,
   * so the negative domain is every key other than `org`.
   */
  test("rejects any key that is not `org`", () => {
    fc.assert(
      fc.property(segment, fc.string({ maxLength: 20 }), (key, value) => {
        fc.pre(key !== "org");
        expect(QuoinConfigSchema.safeParse({ [key]: value }).success).toBe(
          false,
        );
      }),
    );
  });

  test("accepts any non-empty org, and rejects the empty one", () => {
    fc.assert(
      fc.property(fc.string({ maxLength: 30 }), (org) => {
        expect(QuoinConfigSchema.safeParse({ org }).success).toBe(
          org.length > 0,
        );
      }),
    );
  });
});
