// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Agent-IX
//! Full generic EA execution and independent replay of authored input origins.

#![cfg(feature = "campaign")]
#![cfg_attr(not(target_os = "linux"), allow(dead_code, unused_imports))]
#![allow(clippy::expect_used, reason = "fixture setup must fail the test")]

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use std::process::Command;

use engineering_assurance::campaign::{CampaignDefinition, CampaignVerdict, canonical_digest};
use engineering_assurance::producer_execution::{
    CancellationBinding, ContainmentBinding, ContentDigest, ContractBinding, ExecutionBudget,
    ExitCodeBinding, OutputBinding, ProducerDescriptor, StdinBinding,
};
use quoin_measurement::campaign::CampaignOutcome;
use quoin_measurement::campaign::run::{
    BindingFailure, CampaignRunError, InputSource, RunMemberBindings, SelectedInput, run_campaign,
};
use quoin_measurement::campaign::store::run_path;
use quoin_measurement::campaign::verify::verify_retained_campaign;
use quoin_store::digest_bytes_sha256;
use serde_json::{Value, json};

fn git(root: &Path, args: &[&str]) -> Vec<u8> {
    let output = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .output()
        .expect("Git runs");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    output.stdout
}

const PRODUCER: &str = r"import pathlib
import sys

assert pathlib.Path('.git').exists()
if sys.argv[1] == 'prepare':
    pathlib.Path('generated.txt').write_text('sealed generated bytes\n', encoding='utf-8')
elif sys.argv[1] == 'consume':
    assert pathlib.Path(sys.argv[2]).read_text(encoding='utf-8') == 'tracked source bytes\n'
    assert pathlib.Path(sys.argv[3]).read_text(encoding='utf-8') == 'sealed generated bytes\n'
else:
    raise SystemExit(2)
sys.stdout.write('ok')
";

const CHECKER: &str = r"import hashlib
import json
import sys

def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=False).encode()).hexdigest()

with open(sys.argv[sys.argv.index('--input') + 1], encoding='utf-8') as stream:
    selected = json.load(stream)
with open(selected['resultPath'], encoding='utf-8') as stream:
    result = json.load(stream)
accepted = bytes(result['process']['stdout']['bytes']) == b'ok' and result['process']['terminalStatus'] == {'kind':'exit_code','value':0}
receipt = {
    'schema':'fictional.domain-verdict/v1',
    'member':selected['member'],
    'planId':selected['planId'],
    'definitionVersion':selected['definitionVersion'],
    'definitionDigest':selected['definitionDigest'],
    'sourceGraphDigest':selected['sourceGraphDigest'],
    'requestDigest':selected['requestDigest'],
    'resultDigest':selected['resultDigest'],
    'rawArtifactsDigest':digest(selected['rawArtifacts']),
    'rawBundleDigest':selected['rawBundleDigest'],
    'dependenciesDigest':digest(selected['dependencies']),
    'stdoutDigest':result['process']['stdout']['digest'],
    'stderrDigest':result['process']['stderr']['digest'],
    'verdict':'accept' if accepted else 'reject',
    'reasons':[] if accepted else ['fictional-output-mismatch'],
}
with open(sys.argv[sys.argv.index('--output') + 1], 'w', encoding='utf-8') as stream:
    json.dump(receipt, stream, sort_keys=True, separators=(',', ':'))
";

fn plan(id: &str, metric: &str, procedure: &str) -> String {
    format!(
        "---\ntype: MeasurementPlan\nid: {id}\ntitle: Fictional input origin\nstatus: active\nstage: gate\nmetric: {metric}\ndefinition_version: v1\nground_truth_kind: mechanical\nobjective:\n  direction: higher\nstatistical_design:\n  population: one direct process check\n  minimum_population: 1\n  sampling: exhaustive\n  repetitions: 1\n  estimator: count\n  error_model: none -- deterministic fixture\n  uncertainty: none -- exact count\n  decision_rule:\n    comparator: ge\n    threshold: 1\nexecution_procedure: campaign/{procedure}\nprotected_apparatus:\n  - spec/assurance/{id}.md\n  - campaign/{procedure}\n  - campaign/producer.py\n  - campaign/checker.py\nnegative_controls:\n  - kind: apparatus-edit\n    description: exact source-bound input origin\n---\n\n# Fictional input origin\n\n## Comparison and Enforcement\n\nPass when the direct process check is accepted.\n"
    )
}

fn checker_procedure() -> Value {
    json!({
        "schemaVersion":"engineering-assurance.measurement-procedure/v1",
        "producerName":"fictional-checker", "producerVersion":"1",
        "sourceRepository":"fictional/source",
        "arguments":[
            {"kind":"literal","value":"campaign/checker.py"},
            {"kind":"literal","value":"--input"},
            {"kind":"input_artifact","value":"bundle"},
            {"kind":"literal","value":"--output"},
            {"kind":"output_artifact","value":"verdict"}
        ],
        "inputs":[
            {"role":"bundle","required":true},
            {"role":"definition","required":true},
            {"role":"request","required":true},
            {"role":"result","required":true},
            {"role":"rawBundle","required":true}
        ],
        "inputRolePrefixes":[
            {"prefix":"dependency/","required":false},
            {"prefix":"dependency-request/","required":false},
            {"prefix":"dependencyRaw/","required":false}
        ],
        "outputs":[{"role":"verdict","required":true}],
        "responseProtocol":"quoin.process-evidence/v1",
        "responseAdapter":"quoin.process-evidence-adapter",
        "responseAdapterVersion":"1", "repetitions":1, "timeoutMillis":5000
    })
}

fn set(record: &mut Value, key: &str, value: Value) {
    record
        .as_object_mut()
        .expect("fixture record")
        .insert(key.to_owned(), value);
}

fn write_procedures(repo: &Path) {
    let common = json!({
        "schemaVersion":"engineering-assurance.measurement-procedure/v1",
        "producerName":"fictional-tool", "producerVersion":"1",
        "sourceRepository":"fictional/source",
        "responseProtocol":"quoin.process-evidence/v1",
        "responseAdapter":"quoin.process-evidence-adapter",
        "responseAdapterVersion":"1", "repetitions":1, "timeoutMillis":5000
    });
    let mut prepare = common.clone();
    set(
        &mut prepare,
        "arguments",
        json!([
            {"kind":"literal","value":"campaign/producer.py"},
            {"kind":"literal","value":"prepare"}
        ]),
    );
    set(
        &mut prepare,
        "outputs",
        json!([{"role":"generated","required":true}]),
    );
    set(&mut prepare, "inputOrigins", json!([]));
    let mut consume = common;
    set(
        &mut consume,
        "arguments",
        json!([
            {"kind":"literal","value":"campaign/producer.py"},
            {"kind":"literal","value":"consume"},
            {"kind":"input_artifact","value":"spec"},
            {"kind":"input_artifact","value":"generated"}
        ]),
    );
    set(
        &mut consume,
        "inputs",
        json!([
            {"role":"spec","required":true},
            {"role":"generated","required":true}
        ]),
    );
    set(
        &mut consume,
        "inputOrigins",
        json!([
            {"role":"spec","kind":"source_file","sourceRepository":"fictional/source","sourcePath":"source.txt"},
            {"role":"generated","kind":"dependency","dependencyMember":"prepare","dependencyArtifactRole":"generated"}
        ]),
    );
    fs::write(
        repo.join("campaign/prepare.json"),
        serde_json::to_vec(&prepare).expect("prepare JSON"),
    )
    .expect("prepare procedure");
    fs::write(
        repo.join("campaign/consume.json"),
        serde_json::to_vec(&consume).expect("consume JSON"),
    )
    .expect("consume procedure");
}

fn fixture() -> (tempfile::TempDir, CampaignDefinition, String) {
    let repo = tempfile::tempdir().expect("source repository");
    git(repo.path(), &["init", "-q"]);
    fs::create_dir_all(repo.path().join("campaign")).expect("campaign directory");
    fs::create_dir_all(repo.path().join("spec/assurance")).expect("plan directory");
    fs::write(repo.path().join("source.txt"), "tracked source bytes\n").expect("source");
    fs::write(repo.path().join("campaign/producer.py"), PRODUCER).expect("producer");
    fs::write(repo.path().join("campaign/checker.py"), CHECKER).expect("checker");
    for (id, metric, procedure) in [
        ("MP-PREP", "fictional.prepare.score", "prepare.json"),
        ("MP-CONSUME", "fictional.consume.score", "consume.json"),
    ] {
        fs::write(
            repo.path().join(format!("spec/assurance/{id}.md")),
            plan(id, metric, procedure),
        )
        .expect("plan");
    }
    write_procedures(repo.path());
    git(
        repo.path(),
        &["add", "source.txt", "campaign", "spec/assurance"],
    );
    git(
        repo.path(),
        &[
            "-c",
            "user.name=Fixture",
            "-c",
            "user.email=fixture@example.test",
            "commit",
            "-q",
            "-m",
            "source",
        ],
    );
    let revision = String::from_utf8(git(repo.path(), &["rev-parse", "HEAD"]))
        .expect("revision")
        .trim()
        .to_owned();
    let manifest = git(
        repo.path(),
        &["ls-tree", "-r", "-z", "--full-tree", &revision],
    );
    let digest = digest_bytes_sha256(&manifest).as_hex().to_owned();
    let definition = serde_json::from_value(json!({
        "schemaVersion":"engineering-assurance.campaign-definition/v1",
        "id":"fictional-input-origins", "subjectName":"fictional-subject", "subjectVersion":"1",
        "sourceGraph":[{"repository":"fictional/source","revision":revision,"digest":digest}],
        "members":[
            {"name":"prepare","planId":"MP-PREP","definitionVersion":"v1","required":true,
             "checkerProcedure":checker_procedure()},
            {"name":"consume","planId":"MP-CONSUME","definitionVersion":"v1","required":true,
             "dependsOn":["prepare"],"checkerProcedure":checker_procedure()}
        ],
        "completionRule":"all_required"
    }))
    .expect("typed definition");
    (repo, definition, revision)
}

fn bindings(
    repo: &Path,
    revision: &str,
    name: &str,
    checker: bool,
) -> engineering_assurance::campaign::ProcedureBindings {
    let python = fs::canonicalize("/usr/bin/python3").expect("system Python");
    let contract = |kind: &str| ContractBinding {
        kind: kind.to_owned(),
        version: "1".to_owned(),
        revision: revision.to_owned(),
        digest: ContentDigest::of_bytes(kind.as_bytes()),
    };
    engineering_assurance::campaign::ProcedureBindings {
        producer: ProducerDescriptor {
            name: name.to_owned(),
            version: "1".to_owned(),
            source_revision: revision.to_owned(),
            executable: python.to_str().expect("UTF-8 Python path").to_owned(),
            executable_digest: ContentDigest::of_file(&python).expect("Python identity"),
        },
        caller: contract("fictional.caller"),
        capability_root: repo.to_string_lossy().into_owned(),
        environment: BTreeMap::new(),
        inputs: Vec::new(),
        input_origins: None,
        source_tree: None,
        outputs: if checker {
            vec![OutputBinding {
                role: "verdict".to_owned(),
                path: ".quoin-campaign/domain-verdict.json".to_owned(),
                required: true,
            }]
        } else {
            Vec::new()
        },
        output_trees: Vec::new(),
        stdin: StdinBinding::Null,
        containment: ContainmentBinding::ProcessGroupV1 {
            contract: contract("fictional.containment"),
        },
        cancellation: CancellationBinding::Disabled,
        budget: ExecutionBudget {
            timeout_millis: 5000,
            max_stdout_bytes: 4096,
            max_stderr_bytes: 4096,
            max_input_bytes: 8 * 1024 * 1024,
            max_output_artifacts: 8,
            max_output_bytes: 1024 * 1024,
            max_descendants: 8,
            max_concurrency: 1,
        },
        response_protocol: contract("quoin.process-evidence/v1"),
        response_adapter: contract("quoin.process-evidence-adapter"),
        exit_codes: ExitCodeBinding::Any,
    }
}

fn runtime(repo: &Path, revision: &str, prepare: bool) -> RunMemberBindings {
    let inputs = if prepare {
        Vec::new()
    } else {
        vec![
            SelectedInput {
                role: "spec".to_owned(),
                path: "selected/spec.txt".to_owned(),
                executable: false,
                source: InputSource::SourceFile {
                    repository: "fictional/source".to_owned(),
                    path: "source.txt".to_owned(),
                },
            },
            SelectedInput {
                role: "generated".to_owned(),
                path: "selected/generated.txt".to_owned(),
                executable: false,
                source: InputSource::Dependency {
                    member: "prepare".to_owned(),
                    index: 1,
                    artifact_role: "generated".to_owned(),
                },
            },
        ]
    };
    let mut producer = bindings(repo, revision, "fictional-tool", false);
    if prepare {
        producer.outputs = vec![OutputBinding {
            role: "generated".to_owned(),
            path: "generated.txt".to_owned(),
            required: true,
        }];
    }
    RunMemberBindings {
        producer,
        checker: Some(bindings(repo, revision, "fictional-checker", true)),
        inputs,
        timestamp: "2026-09-24T00:00:00Z".to_owned(),
        toolchains: BTreeMap::from([("python".to_owned(), "system-python3".to_owned())]),
        source_remotes: BTreeMap::from([(
            "fictional/source".to_owned(),
            "https://example.invalid/fictional.git".to_owned(),
        )]),
        environment_sources: BTreeMap::new(),
    }
}

/// Trace: FR-114-AC-2, FR-114-AC-3. Provenance: PLAT-1061, TC-1947.
#[cfg(target_os = "linux")]
#[test]
fn tc_1947_two_member_authored_origins_replay_and_rehashed_substitution_rejects() {
    let (repo, definition, revision) = fixture();
    let checkouts = BTreeMap::from([("fictional/source".to_owned(), repo.path().to_path_buf())]);
    let selections = BTreeMap::from([
        ("prepare".to_owned(), runtime(repo.path(), &revision, true)),
        ("consume".to_owned(), runtime(repo.path(), &revision, false)),
    ]);
    let run = run_campaign(
        repo.path(),
        &definition,
        "origin-run",
        &checkouts,
        &selections,
    )
    .expect("bounded two-member campaign");
    assert_eq!(run.verdict, CampaignVerdict::Accepted, "{run:?}");
    let definition_digest = canonical_digest(&definition).expect("definition identity");
    let receipt = verify_retained_campaign(
        repo.path(),
        definition_digest.as_str(),
        "origin-run",
        &checkouts,
    )
    .expect("independent retained replay");
    assert_eq!(
        receipt.decision.verdict,
        CampaignOutcome::Accept,
        "{receipt:?}"
    );

    let consume = run
        .attempts
        .as_ref()
        .expect("attempts")
        .iter()
        .find(|attempt| attempt.member == "consume")
        .expect("consume attempt");
    let collection_id = quoin_measurement::types::ids::CollectionId::parse(
        consume.collection_id.as_deref().expect("collection ID"),
    )
    .expect("valid collection ID");
    let collection_path = quoin_measurement::store::measurement_path(repo.path(), &collection_id);
    let mut collection: Value =
        serde_json::from_slice(&fs::read(&collection_path).expect("collection"))
            .expect("collection JSON");
    assert_eq!(
        collection
            .pointer("/rawEvidence/inputOrigins/declaration")
            .and_then(Value::as_str),
        Some("enforced")
    );
    let origins = collection
        .pointer("/rawEvidence/inputOrigins/inputs")
        .and_then(Value::as_array)
        .expect("origins");
    assert!(origins.iter().any(|item| item.pointer("/source/kind").and_then(Value::as_str) == Some("source_file")));
    assert!(
        origins
            .iter()
            .any(|item| item.pointer("/source/kind").and_then(Value::as_str) == Some("dependency"))
    );
    let dependency = origins
        .iter()
        .position(|item| item.pointer("/source/kind").and_then(Value::as_str) == Some("dependency"))
        .expect("dependency origin");
    *collection
        .pointer_mut(&format!(
            "/rawEvidence/inputOrigins/inputs/{dependency}/source/artifactRole"
        ))
        .expect("dependency artifact role") = json!("substituted-role");
    let altered = serde_json::to_vec(&collection).expect("rehashed collection");
    fs::write(&collection_path, &altered).expect("altered collection");
    let run_file = run_path(repo.path(), "origin-run").expect("retained run path");
    let mut run_value: Value =
        serde_json::from_slice(&fs::read(&run_file).expect("run file")).expect("run JSON");
    let attempt_index = run_value
        .get("attempts")
        .expect("run attempts")
        .as_array()
        .expect("attempts")
        .iter()
        .position(|item| item.get("member").and_then(Value::as_str) == Some("consume"))
        .expect("consume attempt");
    *run_value
        .pointer_mut(&format!("/attempts/{attempt_index}/collectionDigest"))
        .expect("consume collection digest") = json!(digest_bytes_sha256(&altered).as_hex());
    fs::write(
        &run_file,
        serde_json::to_vec(&run_value).expect("rehashed run"),
    )
    .expect("altered run");
    let rejected = verify_retained_campaign(
        repo.path(),
        definition_digest.as_str(),
        "origin-run",
        &checkouts,
    )
    .expect("well-formed tampered run");
    assert_eq!(
        rejected.decision.verdict,
        CampaignOutcome::Reject,
        "{rejected:?}"
    );
}

/// Trace: FR-114-AC-2, FR-114-AC-3. Provenance: PLAT-1043, TC-1942.
/// A dependent member cannot consume an artifact named by a rehashed but
/// independently false checkpoint from a previous partial invocation.
#[cfg(target_os = "linux")]
#[test]
fn tc_1942_resume_rejects_tampered_dependency_checkpoint_before_consumer() {
    let (repo, definition, revision) = fixture();
    let checkouts = BTreeMap::from([("fictional/source".to_owned(), repo.path().to_path_buf())]);
    let mut consume = runtime(repo.path(), &revision, false);
    consume.inputs[0].source = InputSource::File(repo.path().join("missing-first-run.txt"));
    let mut selections = BTreeMap::from([
        ("prepare".to_owned(), runtime(repo.path(), &revision, true)),
        ("consume".to_owned(), consume),
    ]);
    let run_id = "checkpoint-origin-substitution";
    assert!(run_campaign(repo.path(), &definition, run_id, &checkouts, &selections).is_err());
    assert!(!run_path(repo.path(), run_id).expect("run path").exists());
    let checkpoint_dir =
        quoin_measurement::campaign::store::campaigns_root(repo.path()).join("checkpoints");
    let checkpoints: Vec<_> = fs::read_dir(checkpoint_dir)
        .expect("checkpoint directory")
        .map(|entry| entry.expect("checkpoint entry").path())
        .collect();
    assert_eq!(checkpoints.len(), 1, "prepare attempt was retained");
    let checkpoint_path = &checkpoints[0];
    let mut checkpoint: Value =
        serde_json::from_slice(&fs::read(checkpoint_path).expect("checkpoint bytes"))
            .expect("checkpoint JSON");
    assert_eq!(checkpoint["attempt"]["member"], json!("prepare"));
    assert_eq!(
        checkpoint["attempt"]["rawArtifacts"][0]["role"],
        json!("generated")
    );
    let (substituted_digest, _) = quoin_measurement::campaign::store::retain_bytes(
        repo.path(),
        "raw",
        "bin",
        b"substituted generated bytes\n",
    )
    .expect("retain substituted bytes");
    checkpoint["attempt"]["rawArtifacts"][0]["digest"] = json!(substituted_digest);
    fs::write(
        checkpoint_path,
        serde_json::to_vec(&checkpoint).expect("checkpoint JSON"),
    )
    .expect("tamper fixture checkpoint");

    selections.insert("consume".to_owned(), runtime(repo.path(), &revision, false));
    let outcome = run_campaign(repo.path(), &definition, run_id, &checkouts, &selections);
    assert!(
        matches!(
            outcome,
            Err(CampaignRunError::Binding(BindingFailure::IdentityMismatch(
                _
            )))
        ),
        "checkpoint evidence must refuse before consumer: {outcome:?}"
    );
    assert!(!run_path(repo.path(), run_id).expect("run path").exists());
}

/// Trace: FR-114-AC-3. Provenance: PLAT-1043, TC-1944.
/// A sealed producer output tree is still checked from retained bytes, and
/// absence is distinct from changed bytes on independent replay.
#[cfg(target_os = "linux")]
#[test]
fn tc_1944_missing_or_altered_raw_artifact_has_distinct_verdict() {
    let (repo, definition, revision) = fixture();
    let checkouts = BTreeMap::from([("fictional/source".to_owned(), repo.path().to_path_buf())]);
    let selections = BTreeMap::from([
        ("prepare".to_owned(), runtime(repo.path(), &revision, true)),
        ("consume".to_owned(), runtime(repo.path(), &revision, false)),
    ]);
    let run_id = "raw-artifact-refusal";
    let run = run_campaign(repo.path(), &definition, run_id, &checkouts, &selections)
        .expect("accepted two-member campaign");
    assert_eq!(run.verdict, CampaignVerdict::Accepted);
    let prepare = run
        .attempts
        .as_ref()
        .expect("attempts")
        .iter()
        .find(|attempt| attempt.member == "prepare")
        .expect("prepare attempt");
    let artifact = prepare
        .raw_artifacts
        .as_ref()
        .expect("raw inventory")
        .iter()
        .find(|artifact| artifact.role == "generated")
        .expect("generated artifact");
    let raw_path = quoin_measurement::campaign::store::digest_path(
        repo.path(),
        "raw",
        &artifact.digest,
        "bin",
    )
    .expect("raw artifact path");
    let bytes = fs::read(&raw_path).expect("raw artifact bytes");
    let definition_digest = canonical_digest(&definition).expect("definition identity");

    fs::remove_file(&raw_path).expect("remove fixture raw artifact");
    let missing =
        verify_retained_campaign(repo.path(), definition_digest.as_str(), run_id, &checkouts)
            .expect("well-formed run with absent raw artifact");
    assert_eq!(missing.decision.verdict, CampaignOutcome::Inconclusive);
    fs::write(&raw_path, b"altered generated bytes\n").expect("alter raw artifact");
    let altered =
        verify_retained_campaign(repo.path(), definition_digest.as_str(), run_id, &checkouts)
            .expect("well-formed run with altered raw artifact");
    assert_eq!(altered.decision.verdict, CampaignOutcome::Reject);
    fs::write(&raw_path, bytes).expect("restore raw artifact");
}
